version: '3.8'

services:
  app:
    platform: linux/amd64
    container_name: backend
    image: archun39/back:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@cluster0.aelwn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      AI_SERVER_URL: http://ai-server:5050
    depends_on:
      - ai-server
a  ai-server:
    platform: linux/amd64
    container_name: ai-server
    image: archun39/ai:latest
    ports:
      - "5050:5050"

volumes:
  mongo-data: