version: '3.8'

services:
  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/algoanalyzer
      AI_SERVER_URL: http://ai-server:5050
    depends_on:
      - mongo
      - ai-server

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  ai-server:
    container_name: ai-server
    build:
      context: ../algo-analyzer-ai  # AI 서버의 디렉토리 경로
      dockerfile: Dockerfile
    ports:
      - "5050:5050"

volumes:
  mongo-data: