spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: "mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@cluster0.aelwn.mongodb.net/algoanalyzer?retryWrites=true&w=majority&appName=Cluster0"
      database: algoanalyzer
 
server:
  port: 8080 

python:
  api:
    base-url: http://localhost:5050 # FastAPI 서버 주소를 5050번 포트로 변경

logging:
  level:
    root: INFO
    com.algoanalyzer: DEBUG
    org.mongodb.driver: ERROR