spring:
  data:
    mongodb:
      uri: "mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@cluster0.aelwn.mongodb.net/algoanalyzer?retryWrites=true&w=majority&appName=Cluster0"
      database: algoanalyzer
      # 또는 MongoDB Atlas URI 사용 시
      # uri: "mongodb+srv://<username>:<password>@cluster0.mongodb.net/algoanalyzer?retryWrites=true&w=majority"

server:
  port: 8080 

python:
  api:
    base-url: ${AI_SERVER_URL}  # FastAPI 서버 주소를 5050번 포트로 변경

logging:
  level:
    root: INFO
    com.algoanalyzer: DEBUG
    org.mongodb.driver: ERROR